// Generated by CoffeeScript 1.7.1
(function() {
  var CENTER, Control, attribution, smap;

  attribution = 'Map generated by <a href="http://wancharle.github.com/Searchlight">Searchlight</a>,  Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a>';

  CENTER = [-15.799088, -47.865350];

  smap = angular.module('smap', []);

  smap.directive('slMap', function() {
    return {
      scope: {
        json: '=',
        osm: '=?',
        height: '@'
      },
      replace: true,
      link: function(scope, element, attr) {
        var CamadaBasica, mapDiv;
        scope.osm = angular.isDefined(scope.osm) ? $scope.osm : "http://{s}.tile.osm.org/{z}/{x}/{y}.png";
        mapDiv = angular.element("#" + attr.id + " div.map")[0];
        angular.element(mapDiv).height('100%');
        CamadaBasica = L.tileLayer(scope.osm, {
          'attribution': attribution,
          'maxZoom': 18
        });
        scope.map = L.map(mapDiv, {
          layers: [CamadaBasica],
          'center': CENTER,
          'zoom': 13
        });
        return scope.$broadcast('mapInit', attr.id);
      },
      template: "<div><div class='map' sl-control data-map='map'></div></div>"
    };
  });

  Control = L.Control.extend({
    options: {
      position: 'topright'
    },
    onAdd: function(map) {
      var container, stop;
      container = L.DomUtil.create('div', 'searchlight-control leaflet-control-layers');
      container.innerHTML = "<div class='searchlight-opcoes'><ul> </ul></div>";
      container.innerHTML += "<div class='searchlight-analise'></div>";
      stop = L.DomEvent.stopPropagation;
      L.DomEvent.on(container, 'click', stop);
      L.DomEvent.on(container, 'mousedown', stop);
      L.DomEvent.on(container, 'mouseover', stop);
      L.DomEvent.on(container, 'touchstart', stop);
      L.DomEvent.on(container, 'touchend', stop);
      L.DomEvent.on(container, 'dblclick', stop);
      L.DomEvent.on(container, 'scroll', stop);
      L.DomEvent.on(container, 'mousewheel', stop);
      return container;
    }
  });

  smap.directive('slControl', function() {
    return {
      link: function(scope, element, attr) {
        var addControl, hide_opcoes, show_opcoes;
        show_opcoes = function(event) {
          return $(scope.id_opcoes).show();
        };
        hide_opcoes = function(event) {
          return $(scope.id_opcoes).hide();
        };
        addControl = function(e, map_id) {
          var control, id_camadas;
          control = new Control();
          scope.map.addControl(control);
          scope.id_control = "#" + map_id + " div.searchlight-control";
          scope.id_opcoes = "#" + map_id + " div.searchlight-opcoes";
          id_camadas = scope.id_opcoes + "ul";
          $(scope.id_control).mouseenter(show_opcoes);
          $(scope.id_control).bind('touchstart', show_opcoes);
          $("#" + map_id).mouseover(hide_opcoes);
          return $("#" + map_id).bind('touchstart', hide_opcoes);
        };
        return scope.$on('mapInit', addControl);
      }
    };
  });

}).call(this);
