// Generated by CoffeeScript 1.9.2
(function() {
  var Popup;

  Popup = (function() {
    Popup.instances = {};

    Popup.getIS = function(config) {
      return Popup.instances[config.container_id];
    };

    function Popup(config) {
      var container_id, corpo;
      this.config = config;
      container_id = config.container_id;
      Popup.instances[container_id] = this;
      this.id = "popup-" + container_id;
      config.popup_id = this.id;
      corpo = "<div id=\"" + this.id + "\" class=\"modal fade\" data-role='dialog'>";
      corpo += ' <div class="modal-dialog"> <div class="modal-content"> <div class="modal-header"> <h4 class="modal-title"></h4> </div> <div class="modal-body"> </div> <div class="modal-footer"> <button type="button" class="btn btn-default cancelar" data-dismiss="modal">Cancelar</button> <button type="button" class="btn btn-primary" data-dismiss="modal">OK</button> </div> </div><!-- /.modal-content --> </div><!-- /.modal-dialog --> </div>';
      if (!$("#" + this.id).length) {
        $("body").prepend(corpo);
      }
    }

    Popup.prototype.show = function(classe) {
      $("#" + this.id).removeClass('modal-sm modal-lg');
      $("#" + this.id).addClass(classe);
      return $("#" + this.id).modal('show');
    };

    Popup.prototype.close = function() {
      return $("#" + this.id).modal('hide');
    };

    Popup.prototype.setTitle = function(title) {
      return $("#" + this.id + " h4.modal-title").html(title);
    };

    Popup.prototype.setBody = function(body, button_title, callback, cancelar, callback_cancelar) {
      if (button_title == null) {
        button_title = 'OK';
      }
      if (callback == null) {
        callback = null;
      }
      if (cancelar == null) {
        cancelar = false;
      }
      if (callback_cancelar == null) {
        callback_cancelar = null;
      }
      $("#" + this.id + " div.modal-body").html(body);
      $("#" + this.id + " div.modal-footer button.btn-primary").html(button_title);
      if (!cancelar) {
        $("#" + this.id + " div.modal-footer button.cancelar").hide();
      } else {
        $("#" + this.id + " div.modal-footer button.cancelar").show();
      }
      if (callback_cancelar) {
        $("#" + this.id + " div.modal-footer button.cancelar").off('click');
        $("#" + this.id + " div.modal-footer button.cancelar").on('click', callback_cancelar);
      }
      $("#" + this.id).off('hide.bs.modal');
      return $("#" + this.id).on('hide.bs.modal', callback);
    };

    return Popup;

  })();

  module.exports = {
    Popup: Popup
  };

}).call(this);
