// Generated by CoffeeScript 1.9.2
(function() {
  var Config, Dicionario;

  Dicionario = require('./utilidades').Dicionario;

  Config = (function() {
    function Config(apiconf) {
      this.apiconf = apiconf;
      this.apiconf.register(this);
    }

    Config.prototype.parseOpcoes = function(d) {
      this.container_id = d.get('container_id', 'map');
      this.tab_id = "tab-" + this.container_id;
      this.map_id = "map-" + this.container_id;
      this.lista_id = "lista-" + this.container_id;
      this.configuracoes_id = "configuracoes-" + this.container_id;
      this.Icones = d.get('icones', null);
      this.esconder_icones = d.get('esconder_icones', true);
      this.clusterizar = d.get('clusterizar', true);
      this.useBsPopup = d.get('useBsPopup', true);
      this.urlosm = d.get('url_osm', "http://{s}.tile.osm.org/{z}/{x}/{y}.png");
      this.slsUser = d.get('sls_user', '');
      this.slsPassword = '';
      this.urlsls = d.get('url_sls', "http://sl.wancharle.com.br");
      return this.viewerTitle = d.get('viewerTitle', '');
    };

    Config.prototype.toJSON = function() {
      return {
        'container_id': this.container_id,
        'icones': this.icones,
        'esconder_icones': this.esconder_icone,
        'clusterizar': this.clusterizar,
        'useBsPopup': this.useBsPopup,
        'url_osm': this.urlosm,
        'url_sls': this.urlsls,
        'sls_user': this.slsUser,
        'viewerTitle': this.viewerTitle,
        'usarCache': this.usarCache
      };
    };

    return Config;

  })();

  module.exports = {
    Config: Config
  };

}).call(this);
