// Generated by CoffeeScript 1.9.2
(function() {
  var Config, Dicionario;

  Dicionario = require('./utilidades').Dicionario;

  Config = (function() {
    function Config(apiconf) {
      this.apiconf = apiconf;
      this.apiconf.register(this);
    }

    Config.prototype.parseOpcoes = function(d) {
      this.container_id = d.get('container_id', 'map');
      this.tab_id = "tab-" + this.container_id;
      this.map_id = "map-" + this.container_id;
      this.lista_id = "lista-" + this.container_id;
      this.configuracoes_id = "configuracoes-" + this.container_id;
      this.Icones = d.get('icones', null);
      this.esconder_icones = d.get('esconder_icones', true);
      this.ver_mais = d.get('ver_mais', true);
      this.clusterizar = d.get('clusterizar', true);
      this.useBsPopup = d.get('useBsPopup', true);
      return this.urlosm = d.get('osmURL', "http://{s}.tile.osm.org/{z}/{x}/{y}.png");
    };

    Config.prototype.trigger = function(eventName, evObj) {
      return $("#" + this.container_id).trigger(eventName, evObj);
    };

    Config.prototype.on = function(eventName, cb) {
      return $("#" + this.container_id).on(eventName, cb);
    };

    Config.prototype.onChild = function(eventName, childselector, cb) {
      return $("#" + this.container_id).on(eventName, childselector, cb);
    };

    Config.prototype.off = function(eventName) {
      return $("#" + this.container_id).off(eventName);
    };

    Config.prototype.toJSON = function() {
      return {
        'container_id': this.container_id,
        'icones': this.Icones,
        'esconder_icones': this.esconder_icones,
        'ver_mais': this.ver_mais,
        'clusterizar': this.clusterizar,
        'useBsPopup': this.useBsPopup,
        'osmURL': this.urlosm
      };
    };

    return Config;

  })();

  module.exports = {
    Config: Config
  };

}).call(this);
