// Generated by CoffeeScript 1.9.2
(function() {
  var Dados, Popup, TabList;

  Popup = require('./bspopup').Popup;

  Dados = require('./dados').Dados;

  TabList = (function() {
    TabList.instances = {};

    TabList.getIS = function(config) {
      return TabList.instances[config.container_id];
    };

    function TabList(config) {
      this.config = config;
      TabList.instances[this.config.container_id] = this;
      this.popup = Popup.getIS(config);
      this.lista_id = this.config.lista_id;
      this.dados = Dados.getIS(config);
      $("#" + this.config.container_id).on('dados:carregados', (function(_this) {
        return function() {
          return _this.load();
        };
      })(this));
    }

    TabList.prototype.load = function() {
      var cat_name, html, i, j, k, len, len1, obj, ref, ref1, self;
      html = '<table class="table">';
      ref = this.dados.getCategorias();
      for (j = 0, len = ref.length; j < len; j++) {
        cat_name = ref[j];
        ref1 = this.dados.getCatByName(cat_name);
        for (i = k = 0, len1 = ref1.length; k < len1; i = ++k) {
          obj = ref1[i];
          html = html + "<tr><td><a href='javascript:void(0);' data-index='" + i + "' data-cat='" + cat_name + "' class='tablist-item'> " + cat_name + "</a></td><td>" + obj.texto + "</td></tr>";
        }
      }
      html = html + "</table>";
      $("#" + this.lista_id).html(html);
      self = this;
      $("#" + this.lista_id + " a.tablist-item").on('click', function(ev) {
        i = $(this).data('index');
        cat_name = $(this).data('cat');
        return self.open(i, cat_name);
      });
      return console.log('TabList carregado');
    };

    TabList.prototype.open = function(i, cat_name) {
      var obj;
      obj = this.dados.getCatByName(cat_name)[i];
      this.popup.setTitle(obj.cat);
      this.popup.setBody(obj.texto);
      this.popup.show();
      return false;
    };

    return TabList;

  })();

  module.exports = {
    TabList: TabList
  };

}).call(this);
