// Generated by CoffeeScript 1.9.2
(function() {
  var Icones, Marcador, dataview;

  dataview = require('./dataview');

  Icones = (function() {
    function Icones() {}

    Icones.icones = {};

    Icones.getIcone = function(id, config) {
      var i;
      i = Icones.icones[id + ""];
      if (!i) {
        i = new L.icon(config.Icones[id + ""]);
        Icones.icones[id + ""] = i;
      }
      return i;
    };

    return Icones;

  })();

  Marcador = (function() {
    function Marcador(geoItem, config) {
      this.config = config;
      this.m = null;
      this.id = geoItem.hashid;
      this.id_parent = geoItem.id_parent;
      this.latitude = parseFloatPTBR(geoItem.latitude);
      this.longitude = parseFloatPTBR(geoItem.longitude);
      this.texto = geoItem.texto || geoItem.comentarios;
      if (geoItem.icon_id) {
        this.icon = Icones.getIcone(geoItem.icon_id, config);
      } else {
        this.icon = window.SL_ICON_PADRAO;
      }
      if (geoItem.cat) {
        this.cat_id = geoItem.cat_id;
        this.cat = geoItem.cat.replace(",", "").replace('"', '');
      } else {
        this.cat = "descategorizado";
        this.cat_id = 1;
      }
      this.title = geoItem.title;
      this.geoItem = geoItem;
    }

    Marcador.prototype.corrigeImagem = function() {
      return dataview.corrigeImagem(this.geoItem);
    };

    Marcador.prototype.onPopupOpen = function(e) {
      e.marcador = this.m;
      this.config.trigger('marcador:open', e);
      return this.corrigeImagem();
    };

    Marcador.prototype.getTextoParaPopup = function() {
      return dataview.getTextoParaPopup(this.geoItem, this.texto);
    };

    Marcador.prototype.getMark = function() {
      var html, m, p;
      if (this.m === null) {
        p = [this.latitude, this.longitude];
        m = new L.Marker(p);
        m.setIcon(this.icon);
        this.m = m;
        this.m.slinfo = this;
        this.m.on('popupopen', (function(_this) {
          return function(e) {
            return _this.onPopupOpen(e);
          };
        })(this));
        if (this.config.ver_mais) {
          html = m.slinfo.texto + "<p><a class='marker-ver-mais'>ver mais</a></p>";
        } else {
          html = this.getTextoParaPopup();
        }
        this.m.bindPopup(html, {
          'maxWidth': 640,
          autoPan: false
        });
      }
      return this.m;
    };

    return Marcador;

  })();

  module.exports = {
    Marcador: Marcador
  };

}).call(this);
