// Generated by CoffeeScript 1.9.2
(function() {
  var Icones, Marcador;

  Icones = (function() {
    function Icones() {}

    Icones.icones = {};

    Icones.getIcone = function(id, config) {
      var i;
      i = Icones.icones[id + ""];
      if (!i) {
        i = new L.icon(config.Icones[id + ""]);
        Icones.icones[id + ""] = i;
      }
      return i;
    };

    return Icones;

  })();

  Marcador = (function() {
    function Marcador(geoItem, config) {
      this.config = config;
      this.m = null;
      this.id = geoItem.hashid;
      this.id_parent = geoItem.id_parent;
      this.latitude = parseFloatPTBR(geoItem.latitude);
      this.longitude = parseFloatPTBR(geoItem.longitude);
      this.texto = geoItem.texto || geoItem.comentarios;
      if (geoItem.icon_id) {
        this.icon = Icones.getIcone(geoItem.icon_id, config);
      } else {
        this.icon = window.SL_ICON_PADRAO;
      }
      if (geoItem.cat) {
        this.cat_id = geoItem.cat_id;
        this.cat = geoItem.cat.replace(",", "").replace('"', '');
      } else {
        this.cat = "descategorizado";
        this.cat_id = 1;
      }
      this.title = geoItem.title;
      this.geoItem = geoItem;
    }

    Marcador.prototype.onPopupOpen = function(e) {
      var img, p;
      e.marcador = this.m;
      this.config.trigger('marcador:open', e);
      img = document.getElementById('img-' + this.geoItem.hashid);
      p = document.getElementById('pimg-' + this.geoItem.hashid);
      if (img.width > img.height) {
        img.width = 400;
        return p.width = 400;
      } else {
        return img.height = 200;
      }
    };

    Marcador.prototype.getTextoParaPopup = function() {
      var extra, foto, obj;
      extra = "";
      obj = this.geoItem;
      if (obj.fotoURL) {
        if (obj.fotoURL.indexOf('.jpg') > 0) {
          foto = obj.fotoURL.replace('_250x250.jpg', '_400x400.jpg');
        } else {
          foto = obj.fotoURL + "_400x400";
        }
        extra = "<p style='width:400px' id='pimg-" + this.geoItem.hashid + "'><img id='img-" + this.geoItem.hashid + "' src='" + foto + "' /></p>";
      }
      if (obj.youtubeVideoId) {
        extra += "<div><iframe width='320px' height='240px' src='//www.youtube.com/embed/" + obj.youtubeVideoId + "?rel=0' frameborder='0' allowfullscreen></iframe></div> ";
      }
      return this.texto + extra;
    };

    Marcador.prototype.getMark = function() {
      var html, m, p;
      if (this.m === null) {
        p = [this.latitude, this.longitude];
        m = new L.Marker(p);
        m.setIcon(this.icon);
        this.m = m;
        this.m.slinfo = this;
        this.m.on('popupopen', (function(_this) {
          return function(e) {
            return _this.onPopupOpen(e);
          };
        })(this));
        if (this.config.ver_mais) {
          html = m.slinfo.texto + "<p><a class='marker-ver-mais'>ver mais</a></p>";
        } else {
          html = this.getTextoParaPopup();
        }
        this.m.bindPopup(html, {
          'maxWidth': 640,
          autoPan: false
        });
      }
      return this.m;
    };

    return Marcador;

  })();

  module.exports = {
    Marcador: Marcador
  };

}).call(this);
