// Generated by CoffeeScript 1.9.2
(function() {
  var Marcador;

  Marcador = (function() {
    function Marcador(geoItem, config) {
      this.config = config;
      this.m = null;
      this.id = geoItem.hashid;
      this.id_parent = geoItem.id_parent;
      this.latitude = parseFloatPTBR(geoItem.latitude);
      this.longitude = parseFloatPTBR(geoItem.longitude);
      this.texto = geoItem.texto;
      if (geoItem.icon) {
        this.icon = geoItem.icon;
      } else {
        this.icon = window.SL_ICON_PADRAO;
      }
      if (geoItem.cat) {
        this.cat_id = geoItem.cat_id;
        this.cat = geoItem.cat.replace(",", "").replace('"', '');
      } else {
        this.cat = "descategorizado";
        this.cat_id = 1;
      }
      this.title = geoItem.title;
    }

    Marcador.prototype.getMark = function() {
      var html, m, p;
      if (this.m === null) {
        p = [this.latitude, this.longitude];
        m = new L.Marker(p);
        m.setIcon(this.icon);
        this.m = m;
        this.m.slinfo = this;
        html = m.slinfo.texto + "<p><a href='javascript:void(0);' onclick='Searchlight.PopupMarcador.show(\"" + this.config.map_id + "\")'>ver mais</a></p>";
        this.m.bindPopup(html, {
          'maxWidth': 640
        });
      }
      return this.m;
    };

    return Marcador;

  })();

  module.exports = {
    Marcador: Marcador
  };

}).call(this);
