// Generated by CoffeeScript 1.9.2
(function() {
  var PilhaDeZoom,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  PilhaDeZoom = (function() {
    function PilhaDeZoom(sl) {
      this.esta_vazia = bind(this.esta_vazia, this);
      this.hide_redo = bind(this.hide_redo, this);
      this.hide_undo = bind(this.hide_undo, this);
      this.show_redo = bind(this.show_redo, this);
      this.show_undo = bind(this.show_undo, this);
      this.hide = bind(this.hide, this);
      this.show = bind(this.show, this);
      this.refazer = bind(this.refazer, this);
      this.desfazer = bind(this.desfazer, this);
      this.salva_zoom = bind(this.salva_zoom, this);
      var html;
      this.pilha = [];
      this.sl = sl;
      this.id_undozoom = "#" + this.sl.config.map_id + " div.searchlight-undozoom";
      html = "";
      html += "<a class='undo' title='desfazer zoom em grupo' href='#' onclick='SL(\"" + this.sl.config.map_id + "\").control.clusterCtr.pilha_de_zoom.desfazer()'>&nbsp;</a>";
      html += "<a class='redo' title='refazer zoom em grupo' href='#' onclick='SL(\"" + this.sl.config.map_id + "\").control.clusterCtr.pilha_de_zoom.refazer()'>&nbsp;</a>";
      html += "&nbsp;";
      $(this.id_undozoom).append(html);
      $(this.id_undozoom).hide();
      this.undo_visivel = false;
      this.redo_visivel = false;
      this.undozoom_visivel = false;
      this.undo_index = 0;
      this.redo_index = 0;
      this.last_undo = null;
    }

    PilhaDeZoom.prototype.salva_zoom = function() {
      var center, zoom;
      zoom = this.sl.map.getZoom();
      center = this.sl.map.getCenter();
      this.pilha.push([center, zoom]);
      this.last_undo = null;
      this.show_undo();
      this.hide_redo();
      return this.undo_index = this.pilha.length - 1;
    };

    PilhaDeZoom.prototype.desfazer = function() {
      var c, center, ref, z, zoom;
      if (!this.last_undo) {
        z = this.sl.map.getZoom();
        c = this.sl.map.getCenter();
        this.last_undo = [c, z];
        this.pilha.push(this.last_undo);
      }
      if (this.undo_index === (this.pilha.length - 1)) {
        this.undo_index = this.pilha.length - 2;
      }
      ref = this.pilha[this.undo_index], center = ref[0], zoom = ref[1];
      this.undo_index -= 1;
      if (this.undo_index < 0) {
        this.hide_undo();
      }
      this.show_redo();
      return this.sl.map.setView(center, zoom);
    };

    PilhaDeZoom.prototype.refazer = function() {
      var center, ref, zoom;
      if (this.undo_index < 0) {
        this.undo_index = 0;
      }
      ref = this.pilha[this.undo_index + 1], center = ref[0], zoom = ref[1];
      this.undo_index += 1;
      this.sl.map.setView(center, zoom);
      if (this.undo_index >= this.pilha.length - 1) {
        this.hide_redo();
      }
      return this.show_undo();
    };

    PilhaDeZoom.prototype.show = function() {
      if (!this.undozoom_visivel) {
        $(this.id_undozoom).show();
        this.undozoom_visivel = true;
      }
      if (!this.undo_visivel) {
        this.hide_undo();
      }
      if (!this.redo_visivel) {
        return this.hide_redo();
      }
    };

    PilhaDeZoom.prototype.hide = function() {
      if (!this.undo_visivel && !this.redo_visivel) {
        $(this.id_undozoom).hide();
        return this.undozoom_visivel = false;
      }
    };

    PilhaDeZoom.prototype.show_undo = function() {
      this.undo_visivel = true;
      this.show();
      return $(this.id_undozoom + " a.undo").show();
    };

    PilhaDeZoom.prototype.show_redo = function() {
      this.redo_visivel = true;
      this.show();
      return $(this.id_undozoom + " a.redo").show();
    };

    PilhaDeZoom.prototype.hide_undo = function() {
      $(this.id_undozoom + " a.undo").hide();
      this.undo_visivel = false;
      return this.hide();
    };

    PilhaDeZoom.prototype.hide_redo = function() {
      $(this.id_undozoom + " a.redo").hide();
      this.redo_visivel = false;
      return this.hide();
    };

    PilhaDeZoom.prototype.esta_vazia = function() {
      return this.pilha.length === 0;
    };

    return PilhaDeZoom;

  })();

  module.exports = {
    PilhaDeZoom: PilhaDeZoom
  };

}).call(this);
