// Generated by CoffeeScript 1.9.2
(function() {
  var BIBLIOTECA, CEMUNI, CT, Config, Controle, Dados, Popup, PopupMarcador, SENADO_FEDERAL, Searchlight, TabConfiguracoes, TabList, UFES, attribution, referencia_atual, sl_referencias,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Dados = require('./dados').Dados;

  Controle = require('./controle').Controle;

  Config = require('./config').Config;

  PopupMarcador = require('./popupMarcador').PopupMarcador;

  TabList = require('./lista').TabList;

  TabConfiguracoes = require('./tabConfiguracoes').TabConfiguracoes;

  Popup = require('./bspopup').Popup;

  SENADO_FEDERAL = [-15.799088, -47.865350];

  UFES = [-20.277233, -40.303752];

  CT = [-20.273530, -40.305448];

  CEMUNI = [-20.279483, -40.302690];

  BIBLIOTECA = [-20.276519, -40.304503];

  attribution = 'Map generated by <a href="http://wancharle.github.com/Searchlight">Searchlight</a>,  Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a>';

  L.Icon.Default.imagePath = "/sl/images/leaflet";

  window.SL_ICON_CLUSTER = new L.DivIcon({
    html: '<div><span>1</span></div>',
    className: 'marker-cluster marker-cluster-small',
    iconSize: [40, 40],
    popupAnchor: [0, -35]
  });

  window.SL_ICON_PADRAO = new L.Icon.Default();

  referencia_atual = null;

  sl_referencias = {};

  window.SL = function(map_id) {
    "funcao global para pegar a referencia do objeto mapa";
    return sl_referencias[map_id];
  };

  Searchlight = (function() {
    function Searchlight(opcoes) {
      if (opcoes == null) {
        opcoes = {};
      }
      this.esconderCamadaMarkers = bind(this.esconderCamadaMarkers, this);
      this.mostrarCamadaMarkers = bind(this.mostrarCamadaMarkers, this);
      this.autoZoom = bind(this.autoZoom, this);
      this.bindEvents = bind(this.bindEvents, this);
      this.create = bind(this.create, this);
      this.getIS = bind(this.getIS, this);
      this.slsapi = new SLSAPI(opcoes);
      this.slsapi.on(SLSAPI.Config.EVENT_READY, (function(_this) {
        return function(id) {
          _this.config = new Config(_this.slsapi.config);
          sl_referencias[_this.config.map_id] = _this;
          _this.create();
          _this.bindEvents();
          $('.collapse').collapse();
          _this.dados = new Dados(_this);
          _this.dados.get_data();
          _this.tabList = new TabList(_this.config);
          return _this.tabConfiguracoes = new TabConfiguracoes(_this.config, _this.dados);
        };
      })(this));
    }

    Searchlight.prototype.getIS = function() {
      return "SL(\"" + this.config.map_id + "\")";
    };

    Searchlight.prototype.create = function() {
      $("#" + this.config.container_id).html("<ul class='nav nav-tabs' role='tablist'> <li class='active'><a data-toggle='tab' href='#" + this.config.tab_id + "'>Mapa</a></li> <li><a data-toggle='tab' href='#tab-" + this.config.lista_id + "'>Lista</a></li> <li><a data-toggle='tab' href='#tab-" + this.config.configuracoes_id + "'>Configurações</a></li> </ul> <div class='tab-content'> <div class='tab-pane active' id='" + this.config.tab_id + "'><div id='" + this.config.map_id + "' > </div> </div> <div class='tab-pane' id='tab-" + this.config.lista_id + "' ><div class='searchlight-tab' id='" + this.config.lista_id + "'> </div> </div> <div class='tab-pane' id='tab-" + this.config.configuracoes_id + "' ><div class='searchlight-tab' id='" + this.config.configuracoes_id + "'> </div> </div> </div> ");
      this.bsPopup = new Popup(this.config);
      this.CamadaBasica = L.tileLayer(this.config.urlosm, {
        'attribution': attribution,
        'maxZoom': 18
      });
      this.map = L.map(this.config.map_id, {
        layers: [this.CamadaBasica],
        'center': SENADO_FEDERAL,
        'zoom': 13
      });
      if (this.config.clusterizar) {
        this.markers = new L.MarkerClusterGroup({
          zoomToBoundsOnClick: false
        });
      } else {
        this.markers = new L.FeatureGroup();
      }
      this.map.addLayer(this.markers);
      return this.control = new Controle(this);
    };

    Searchlight.prototype.bindEvents = function() {
      this.slsapi.on(SLSAPI.dataPool.DataPool.EVENT_LOAD_START, (function(_this) {
        return function() {
          console.log('dados carregando');
          return _this.map.spin(true);
        };
      })(this));
      return SLSAPI.events.on(this.slsapi.config.id, Dados.EVENT_DATA_LOADED, (function(_this) {
        return function() {
          return _this.onDataLoaded();
        };
      })(this));
    };

    Searchlight.prototype.onDataLoaded = function() {
      console.log('segundo evento');
      this.markers.clearLayers();
      this.dados.addMarkersTo(this.markers);
      this.control.addCatsToControl(this.config.map_id);
      this.control.atualizarIconesMarcVisiveis();
      if (this.map.getBoundsZoom(this.markers.getBounds()) === this.map.getZoom()) {
        this.executandoZoomDeCarregamento = false;
      } else {
        this.map.fitBounds(this.markers.getBounds());
        this.executandoZoomDeCarregamento = true;
      }
      this.markers.fire("data:loaded");
      if (this.executandoZoomDeCarregamento === false) {
        $("#" + this.config.container_id).trigger('mapa:carregado');
      }
      return this.autoZoom();
    };

    Searchlight.prototype.autoZoom = function() {
      return this.map.fitBounds(this.markers.getBounds());
    };

    Searchlight.prototype.mostrarCamadaMarkers = function() {
      this.map.addLayer(this.markers);
      return this.map.setView(this.map_ultimo_center, this.map_ultimo_zoom);
    };

    Searchlight.prototype.esconderCamadaMarkers = function() {
      this.map.removeLayer(this.markers);
      this.map_ultimo_zoom = this.map.getZoom();
      return this.map_ultimo_center = this.map.getCenter();
    };

    Searchlight.prototype.openMarker = function(lat, lon, hashid) {
      var bounds;
      this.map.setView([lat, lon], 14, {
        reset: true
      });
      bounds = this.map.getBounds();
      return this.markers.eachLayer(function(marker) {
        if (bounds.contains(marker.getLatLng()) && marker.slinfo.id === hashid) {
          return marker.fireEvent('click');
        }
      });
    };

    return Searchlight;

  })();

  Searchlight.Popup = Popup;

  Searchlight.PopupMarcador = PopupMarcador;

  window.Searchlight = Searchlight;

}).call(this);
